#!/bin/sh

ENV_INPUT=$1
shift
STATES="$*"
if [ -z "$ENV_INPUT" ]; then 
  echo "Usage: $0 <sql|stage|prod> [client_state_code...]"
  exit
fi

OUTPUTDIR_UNIX=/c/temp/mongo_backup
mkdir -p $OUTPUTDIR_UNIX

if [ -z "$STATE" ]; then
  STATES='la ne'
fi

for ABBR in ${STATES}; do

  case "$ABBR" in 
    la) CLIENT=louisiana ;;
    ne) CLIENT=nebraska ;;
  esac

  case "$ENV_INPUT" in
# This does not work. Should not pass --username for local DB?
#    [Ll][Oo][Cc][Aa][Ll]) 
#	   ENV_NAME=
#      HOST=localhost
#      PORT=27017
#      USERNAME=${CLIENT}iatdev
#      PSWD=falcon1
#      ;;
    
    [Ss][Qq][Aa]) 
      ENV_NAME=sqa
      # Dump from the immediate replication, slave server.
      HOST=dcrmdbd005
      PORT=31001
      USERNAME=${CLIENT}iatdev
      PSWD=falcon1
      ;;
    
    [Ss][Tt][Aa]*) 
      ENV_NAME=staging
      # Dump from the immediate replication, slave server.
      HOST=dcrmdbd005
      PORT=31001
      USERNAME=${CLIENT}iatdev
      PSWD=falcon1
      ;;
    
    [Pp][Rr][Oo][Dd]*) 
      ENV_NAME=prod
      # Dump from the immediate replication, slave server.
      HOST=dcrmdbp007
      PORT=31001
      USERNAME=${CLIENT}iatprod
      ;;
  esac

  DB=${CLIENT}_iat_${ENV_NAME}
  OUTPUTFILE=${ENV_NAME}_${ABBR}_dump_$(date '+%Y-%m-%d_%H%M%S' --utc)

  echo -e "\n\n"
  echo mongodump --quiet --excludeCollection=system.users --port=$PORT --db=$DB --host=$HOST --username=$USERNAME --password=$PSWD --out="$(cygpath -w $OUTPUTDIR_UNIX/)$OUTPUTFILE" 

  pushd $OUTPUTDIR_UNIX
  #tar -czvf "../${OUTPUTFILE}.tgz" .
  
done

