GET https://la-iat.drcedirect.com/la/iatUtility/ping
###

GET http://10.200.15.229/la/iatUtility/ping
###
GET http://10.200.63.118/la/iatUtility/ping
###

### The following key is for production (and development ?).
GET http://dcciatp-05eed232f22fbf123/la/userToken/serviceUserToken

{
  "serviceId": "IATUTILITY",
  "serviceTokenSecretKey": "d7039481-0d7f-4db5-a5dd-3fd1ff72f88d",
  "stateCode": "la",
}
> {% client.global.set("iatServiceToken", response.body.serviceTokenSecretKey); %}

###

GET http://dcciatp-05eed232f22fbf123.datarecognitioncorp.com/la/iatUtility/serverInfo

{ "serviceToken": "{{iatServiceToken}}" }

###
GET http://dcciatp-0d91b985e6bf9fd2a.datarecognitioncorp.com/la/iatUtility/serverInfo

{ "serviceToken": "{{iatServiceToken}}" }

###

