GET {{ideasEndpoint}}/webservices/REST/1.0/iat.svc/itemsandpassages/LA?idlist=1013653%2C137220
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{ecaBearer}}

<> 2019-05-17T033736.200.txt
<> 2018-10-08T085109.200.json
<> 2018-10-08T085021.403.json
<> 2018-10-08T020219.200.json
<> 2018-10-07T084114.200.json

###
# Different environment URIs:
#   GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
#   GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc
#
# Using Edirect:
#   SQA: http://ideasdevapp01/test.ideas/webservices/REST/1.0/iat.svc
#   Prod: http://dcwidap014/ideas/webservices/REST/1.0/iat.svc
