GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc/comments/LA/1011725
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IklBVEVhZ2xlVXNlckBnbWFpbC5jb20iLCJpYXQiOjE1MzM1NzY0OTcsImV4cCI6MTUzMzU3ODI5NywiaXNzIjoiZWNhLWRyYyIsInN1YiI6IkJDOUU4RTRGLUMyRDMtNDU1RS04MDNDLTlGQjY5RDc3QTZBQiJ9.eQAbG8R1a1Esy0JfqYI9dDnW-O-EtArNKDj6MkLo2XGii3pJ4AR2-sEH5_UgiYrQjhNmuBtU4LzTTkIdQv8p4JZzhTePIc6kkVvN9UfXWUbgvOSeu8_5qrIsK1SufqtTLNnMaVRDFITSqbJD69cn1YBko2L9gGYJrDfdGlo5Y--6nRdGb_9pYVjF1keUlzYTimBgoPSjmLCIedLbQZJ8RM2u3c7G1_d7UW8AL1e5yGoke21sy5wyuLxxcp5vtZ2A88FOgqI4sObCAri1jXnQ__-Sl0aYxtnY3COcUIDndyp1BMOcpN-XVm9B4Sct1ManvWxuRSWWgFNtgeydxUWjkg

<> 2018-08-06T124239.400.json
<> 2018-08-06T122845.200.json
<> 2018-07-11T084242.200.json

###
Different environment URIs:
GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc

Using Edirect:
SQA: http://ideasdevapp01/test.ideas/webservices/REST/1.0/iat.svc
Prod: http://dcwidap014/ideas/webservices/REST/1.0/iat.svc
