GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc/items/LA/1014245
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdjb2FrbGV5QGRhdGFyZWNvZ25pdGlvbmNvcnAuY29tIiwiaWF0IjoxNTQ0MDQ5ODcxLCJleHAiOjE1NDQwNTE2NzEsImlzcyI6ImVjYS1kcmMiLCJzdWIiOiI4MTUxNzg4Ny0yNDBDLTQ4NDEtODM2MS0wMzgxQTVGNEQ1MkMifQ.Ie-byBsc_lUnK5flcJgcJ6i9l0NTX_hqz7SnkhWeblm0Gu3eyAySqD_nw-RqGNE-PvA0IVemKxLj5BwIMpT2EnMs6ETBEow4cNZ32x-8pQKTbMwVfkiPrV9gSMHvC1LSsveN2vhXyU5wtPTpT9WNMf1hA3Cr_3kP3XaHjg3Af0UAUVi2_zOPBkqS8AdMoVOnwQhYAy5c-wa5ufl4el9tqcBIyFJ4oreo47oCL-WPF9QK3dlSSg_pnmpVBoCeu1RwyixU8-gSuzJ96GqYRNq4bmskC2SpjCnF1np9wWUhaQ3Ib6AnDnNEswOUEpYvJfQ1L3S8ASJBkfLPHwovfqM49w

<> 2018-10-08T085109.200.json
<> 2018-10-08T085021.403.json
<> 2018-10-08T020219.200.json
<> 2018-10-07T084114.200.json

###
# Different environment URIs:
#   GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
#   GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc
#
# Using Edirect:
#   SQA: http://ideasdevapp01/test.ideas/webservices/REST/1.0/iat.svc
#   Prod: http://dcwidap014/ideas/webservices/REST/1.0/iat.svc
