###
GET {{ideasEndpoint}}/webservices/REST/1.0/iat.svc/items/LA/1017960
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{ecaBearer}}

###
GET {{ideasEndpoint}}/webservices/REST/1.0/iat.svc/items/online/LA/1017960
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{ecaBearer}}


###
# Different environment URIs:
#   GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
#   GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc
#
# Using Edirect:
#   SQA: http://ideasdevapp01/test.ideas/webservices/REST/1.0/iat.svc
#   Prod: http://dcwidap014/ideas/webservices/REST/1.0/iat.svc
