PUT https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc/items/LA/570781
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdjb2FrbGV5QGRhdGFyZWNvZ25pdGlvbmNvcnAuY29tIiwiaWF0IjoxNTQ2ODgwODIzLCJleHAiOjE1NDY4ODI2MjMsImlzcyI6ImVjYS1kcmMiLCJzdWIiOiI4MTUxNzg4Ny0yNDBDLTQ4NDEtODM2MS0wMzgxQTVGNEQ1MkMifQ.YAkteKQ5Ru2osl7OjvnwCOm_I8GCTIs0cXqeFVKNMxXKS-kLQsBLhrWeZR7K5dv8qPJTu-pL7-6WXO0JOceEZiUvxl7pd0hooeN1RFVA85UTA8EhT7Om1XFi7zqAa-bwYjnb-ZfXrdMWn-mnkYOwzsEDNvdmDM7CUVKFT135_-rcTTunDBCKT2JXZ87a3Ak3q88XYcTztNc-rjDw9WyXlgZKeSvu0ryXLGzgRPJ7o9WB5lQLUiaz1bsrPRm2kxCpjBgluEHYPnzxAiqSUicuI86do4wGmJnBOMcKNmcxvRgtCoozzgi3ag0N_PWtC57QO4W6uV_dxTUiZltc6grN2w

{
    "iatStatus": "retired",
    "itItemID": 570781
}

<> 2018-10-08T085641.404.html

###
# Different environment URIs:
#   GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
#   GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc
#
# Using Edirect:
#   SQA: http://ideasdevapp01/test.ideas/webservices/REST/1.0/iat.svc
#   Prod: http://dcwidap014/ideas/webservices/REST/1.0/iat.svc
