GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc/itemsandcount/LA?query=((itStatus%3DExternal%2CFTReady%2CData%2COPReady)%2C(itquicksearch%3D*STD%3A%25800755%2C800805%2C833438%2C833439%2C833440%2C833441%2C870418%2C880477*))&sort=itGradeSort++asc&pagesize=15&pagenumber=4
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdDb2FrbGV5IiwiaWF0IjoxNTM5MDM4NjY5LCJleHAiOjE1MzkwNDA0NjksImlzcyI6ImVjYS1kcmMiLCJzdWIiOiJGOUVCQUIwQS1FNDJDLTRGMDctOUUwMy04RUEzQzU0NTE5QTEifQ.r2-mlDhuN3ZBZE_mRyM52pNA1Wj1XmsTxVBM2lVr7Z8yVdiAikxECIwl5P5-jYKh2lhFqrs3Ev7D_jJEeJmSqKKjC7EuL3ZpvsmPm3tYOdkpZtfV1MhUhNIM_QIfx0Jroyg-e2U2AaUR4g35g1jn1gcwevPWwmUOO6nPRhwToQqUBmybufG0_UwGdFd2SGg36cJ2B3214WReVxTob7SjpiMZ1p-IymGG4GPr42EVSb599Y9kDAWEmTmjs5MnBavLLRWHnvapf-uo7HlXPVZd0M6lmLNSzXMCPX9FsrkbGvWNCL8a6RusugnQG9ke05Ma9J2jR6ur6-z9HRtzF1aTAA


<> 2018-07-26T012400.404.html
<> 2018-07-26T012348.404.html
<> 2018-07-26T012159.200.json
<> 2018-07-26T011954.403.json
<> 2018-07-11T084242.200.json

###
Different environment URIs:
GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc

Using Edirect:
SQA: http://ideasdevapp01/test.ideas/webservices/REST/1.0/iat.svc
Prod: http://dcwidap014/ideas/webservices/REST/1.0/iat.svc
