GET http://iatudb-prod.datarecognitioncorp.com/iatudbservice/510842/TestSessionMixedItemPerformanceReport?TestSessionID~eq=501243956
Authorization: 3Direct@1nf0rm
Content-Type: application/json; charset=UTF-8

###
