#!/bin/sh

TMPDIR=$TMP/$(basename $0).tmp
rm -rf $TMPDIR
mkdir $TMPDIR
#trap "rm -rf $TMPDIR" 0 1 2 3 9 15
npm doctor > $TMPDIR/npm_doctor.out 2>&1 &

npm_cache_dir_win=$(npm config get prefix)
npm_cache_dir_unix=$(cygpath -u $npm_cache_dir_win)
#npm_globals=$(cd $npm_cache_dir_unix ; find . -maxdepth 1 -type f ! -name \*.cmd ! -name \*.log ! -name ! -name \*.locki | grep -v 'ngc\|run-[ps]\|sass\|tsc\|tsserver\|_ts-node' | sed -e 's;\./;;g')
npm_globals="bower grunt gulp karma ng ng-packagr node nodemon protractor sass tsc tslint ts-node yarn yarnpkg yo"

for npm_tool in python ruby node $npm_globals; do 
   echo -e "\n\nNPM TOOL: $npm_tool \n" 	> $TMPDIR/${npm_tool}.out
   type -a $npm_tool 				>> $TMPDIR/${npm_tool}.out
   $npm_tool --version 				>> $TMPDIR/${npm_tool}.out 2>&1 &
done

echo -e "\n\nNPM TOOL: npm" 		> $TMPDIR/npm.out
npm -v					>> $TMPDIR/npm.out
echo -e "\n\nNPM configuration: " 	>> $TMPDIR/npm.out
npm config list -l 			>> $TMPDIR/npm.out

wait
cat $TMPDIR/*.out

