#!/bin/sh

MONTHS=(Dum Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec)

buildDate=$(grep build.date | cut -d'"' -f4)
monthAbbr=$(echo $buildDate | awk '{print $2}')
monthNo=0
while [ "${MONTHS[$monthNo]}" != "$monthAbbr" ] && [ $monthNo -le 12 ]; do
   monthNo=$(( $monthNo + 1 ))
done

git fetch --all
echo -e "\nLast build: $buildDate"
git log --since=$(echo $buildDate | awk '{printf("%s-%s-%sT%s", $6,'$monthNo',$3,$4)}')

