#!/bin/sh

CLIENT=$(echo $0 | cut -d'-' -f2)
ENV=$(echo $0 | cut -d'-' -f3)

if [ -z "$CLIENT" ] || [ -z "$ENV" ]; then 
    echo "Unknown environment: $ENV"
else
    LOGDIR=/c/dev/wksp/temp/${CLIENT}_${ENV}_logs

    if [ $(ls -1 ${LOGDIR}/dcriat*/iat.log*.gz | grep -cF '.gz') -gt 0 ]; then
        gunzip ${LOGDIR}/dcriat*/iat.log*.gz
    fi
    FILES=${@:-${LOGDIR}/dcriat*/iat.log*}

    cat $FILES | grep -n ' ERROR \|Exception\|^\sat \|null' | grep -v 'UserActivityFilters  << null\|UserTokenController\|Successfully authenticated through eDirect\|deprecated ItemSearchCommand' | grep -1 'ERROR \|Exception\|:\sat \|null'
fi

