#!/bin/sh

if [ -z "$1" ]; then
   echo 'Usage: <passage_id>'
fi

while [ -n "$1" ]; do
   echo -e "\t Ideas ID: $1"
   curl -s http://ideasprod/ideas/webservices/REST/1.0/iat.svc/passages/LA/$1 | sed -e 's/,/,\n/g' | grep 'Status\|Error'
   shift
done

