#!/bin/sh
 
devCfg=${1:-dev_sqa_la}
cfgDir=/c/dev/wksp/save/iat-env-config

if [ -n "$devCfg" -a -r "$cfgDir/$devCfg" ]; then 
   targetCfgDir=$(pwd | sed -e 's;\(/c/dev/wksp/[^/]*\).*;\1/config/local/iat/;')
   set -x
   cp $cfgDir/$devCfg/*.groovy $targetCfgDir
   set +x
else
   cd $cfgDir
   echo "Saved configuration file sets:"
   find [a-zA-Z]* -maxdepth 0 -type d | sed -e 's;\./;;g'
fi

