#!/bin/sh

time=30
while true; do 
   out=$(curl -kisSL https://la-iat-sqa.drcedirect.com/la/iatUtility/ping)
   if [ -n "$(echo $out | grep BUILD_NUMBER)" ]; then 
      echo $out
      break
   else
      echo "Sleeping for $time seconds."
   fi
   sleep $time
   echo ''
done

