### Returns a 404 and a list of valid endpoints
GET {{formRecognitionUrl}}
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json

###
GET {{formRecognitionUrl}}/status
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json

###
GET {{formRecognitionUrl}}/forms
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json

###
GET {{formRecognitionUrl}}/masterimage
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json

###
GET {{formRecognitionUrl}}/pending
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json

###
GET {{formRecognitionUrl}}/scans
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json

###
GET {{formRecognitionUrl}}/sessions
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json

###
GET {{formRecognitionUrl}}/sessions/unsubmitted
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json

##### The following only work in upper environments that define API Gateway BasePath Mappings. #####

###
GET {{formRecognitionUrl}}/live/status
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json
###
GET {{formRecognitionUrl}}/blue/status
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json
###
GET {{formRecognitionUrl}}/green/status
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json
###
GET {{formRecognitionUrl}}/blue/pending
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json
###
