GET https://eca-form-recognition-service-dev.awcl.drcedirect-le.com/clients
Authorization: Bearer {{ecaBearer}}
Accept: */*
Content-Type: application/json

###
GET https://eca-form-recognition-service-dev.awcl.drcedirect-le.com/pending
Authorization: Bearer {{ecaBearer}}
Accept: */*
Content-Type: application/json

###
