GET {{onlineScoringUrl}}/live/status
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json

###
GET {{onlineScoringUrl}}/live/swagger
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json

###
GET {{onlineScoringUrl}}/live/swagger/ui
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json

###
GET {{onlineScoringUrl}}/live/forms/595211
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json

###
GET {{onlineScoringUrl}}/live/forms/595219
Authorization: Bearer {{ecaBearer}}
Content-Type: application/json

###
