GET {{onlineScoringService}}/status
Authorization: Bearer {{ecaBearer}}
Accept: */*
Content-Type: application/json

###

GET {{onlineScoringService}}/swagger
Authorization: Bearer {{ecaBearer}}
Accept: */*
Content-Type: application/json

###

GET {{onlineScoringService}}/forms/595211
Authorization: Bearer {{ecaBearer}}
Accept: */*
Content-Type: application/json

###

GET {{onlineScoringService}}/forms/595219
Authorization: Bearer {{ecaBearer}}
Accept: */*
Content-Type: application/json

###
