
### QTI v2 Success: given manifest.xml URL.
POST {{qtiValidationUrl}}/v1/validatePackage
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{ecaBearer}}

{
  "packageRootUrl":"s3://us-east-2-qss-assets-sqa/temp/qvs/examples/package/imsmanifest.xml",
  "packageId":"package/imsmanifest.xml-{{$timestamp}}"
}

### QTI v3 Success: I9b-RP-Fixed-Templates
POST {{qtiValidationUrl}}/v1/validatePackage
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{ecaBearer}}

{
  "packageRootUrl": "s3://us-east-2-qss-assets-{{envAbbr}}/temp/qvs/qti-3.0-level-1/I9b-RP-Fixed-Templates",
  "packageId": "I9b-RP-Fixed-Templates-{{$timestamp}}"
}
> {% execArn = response.body['executionArn']; client.log('Execution ARN: ' + execArn); client.global.set('lastQVSExecutionArn', execArn); %}

### QTI v3 Error: manifest-incorrect-resource-identifiers
POST {{qtiValidationUrl}}/v1/validatePackage
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{ecaBearer}}

{
  "packageRootUrl": "s3://us-east-2-qss-assets-{{envAbbr}}/temp/qvs/validation-errors/qti-3.0-level-1/manifest-incorrect-resource-identifiers",
  "packageId": "manifest-incorrect-resource-identifiers-{{$timestamp}}"
}
> {% execArn = response.body['executionArn']; client.log('Execution ARN: ' + execArn); client.global.set('lastQVSExecutionArn', execArn); %}

### QTI v3 Error: manifest-missing-file-from-package
POST {{qtiValidationUrl}}/v1/validatePackage
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{ecaBearer}}

{
  "packageRootUrl": "s3://us-east-2-qss-assets-{{envAbbr}}/temp/qvs/validation-errors/qti-3.0-level-1/manifest-missing-file-from-package",
  "packageId": "manifest-missing-file-from-package-{{$timestamp}}"
}
> {% execArn = response.body['executionArn']; client.log('Execution ARN: ' + execArn); client.global.set('lastQVSExecutionArn', execArn); %}

### QTI v3 Error: manifest-extra-files-in-package
POST {{qtiValidationUrl}}/v1/validatePackage
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{ecaBearer}}

{
  "packageRootUrl": "s3://us-east-2-qss-assets-{{envAbbr}}/temp/qvs/validation-errors/qti-3.0-level-1/manifest-extra-files-in-package",
  "packageId": "manifest-extra-files-in-package-{{$timestamp}}",
  "checkForExtraFilesInPackage": true
}
> {% execArn = response.body['executionArn']; client.log('Execution ARN: ' + execArn); client.global.set('lastQVSExecutionArn', execArn); %}

### QTI v3 Error: qti-mismatched-versions
POST {{qtiValidationUrl}}/v1/validatePackage
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{ecaBearer}}

{
  "packageRootUrl": "s3://us-east-2-qss-assets-{{envAbbr}}/temp/qvs/validation-errors/qti-3.0-level-1/qti-mismatched-versions",
  "packageId": "qti-mismatched-versions-{{$timestamp}}",
  "checkForExtraFilesInPackage": true
}
> {% execArn = response.body['executionArn']; client.log('Execution ARN: ' + execArn); client.global.set('lastQVSExecutionArn', execArn); %}

### Get status of last QVS execution.
POST {{qtiValidationUrl}}/v1/getValidationStatus
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{ecaBearer}}

{
  "executionArn": "{{lastQVSExecutionArn}}"
}
> {% client.log('Execution ARN: ' + client.global.get('lastQVSExecutionArn')); %}


###### @see https://www.jetbrains.com/help/idea/2021.2/exploring-http-syntax.html#using_request_vars
