POST {{apiGatewayUrl}}/eca-security-service/all-{{envName}}-v0/v0/authenticate?token={{ecaBearer}}
Accept: */*
Content-Type: application/json

{"token":"{{ecaBearer}}"}

###
Replace everything in the URI after 'token=' AND the value for 'token' in the POST data with the ECA token value.
