GET {{apiGatewayUrl}}/eca-security-service/all-{{envName}}-v0/v0/authorize/{{ecaBearer}}/acls
Accept: */*
Authorization: Bearer {{ecaBearer}}
Cache-Control: no-cache
Content-Type: application/json

###
