#!/bin/sh

echo -e "\nIn glencoakley.\n"
cd /c/dev/wksp/my_git_server/glencoakley/shell-env 
git checkout master
cp -rup /c/dev/config/ .
cp -rup /c/dev/cmd/ .
cp -rup $HOME/scripts/ .
# Remove large ruby plugin and rebuildable IntelliJ caches.
rm -rf idea.*/config/plugins/ruby
rm -rf idea.*/config/system/{caches,index}

git add config cmd scripts 2> /dev/null | grep -v '^ create mode '
echo -e "\nPushing to glencoakley.\n"
git commit -m "Snapshot of env on $(date)."
git push


echo -e "\nIn drc-gcoakley.\n"
cd /c/dev/wksp/my_git_server/drc-gcoakley/sandbox
git checkout shell-env
# Don't copy the .git directory!
cp -rup /c/dev/wksp/my_git_server/glencoakley/shell-env/{config,cmd,scripts} .

git add config cmd scripts 2> /dev/null | grep -v '^ create mode '
echo -e "\nPushing to drc-gcoakley.\n"
git commit -m "Snapshot of env on $(date)." | grep -v '^ create mode '
git push
