#!/bin/sh

# Use a directory in a location that we don't care about but, that is not going to be deleted. 
# The best place for DIR would be /var/$USER/Chrome_RI_Dev but, that requires sudo and permissions to write to it.
# But, this will try it in case somebody wants to put there temporary Chrome user data directory there. 
# Otherwise, this just will just put it under their user home directory.
DIR=/var/$USER/Chrome_RI_Dev
if [ ! -d "$DIR" ]; then 
    DIR=~/temp/Chrome_RI_Dev
    if [ ! -d "$DIR" ]; then 
        mkdir $DIR
    fi
fi

# -a  Specifies the application to use for opening the file.
# -n  Open a new instance of the application(s) even if one is already running.
# --user-data-dir is (or will be) required when specifying --disable-web-security
open -na Google\ Chrome --args --allow-file-access-from-files --disable-web-security --user-data-dir=$DIR $@ http://local.accelus.com

