#!/bin/sh

TMPFILE=$TMP/$(basename $0).$(echo $@ | tr ' ' '_').tmp
#trap "rm -f $TMPFILE" 0 1 2 3 9 15

EXCL_FILE=$(which $0)-exclusions.txt
diff -X $EXCL_FILE -r $@  2>&1 > $TMPFILE
grep '^diff ' $TMPFILE
read -sn 1 -p 'Press enter to continue...  '
less $TMPFILE
echo "Output is in: $TMPFILE"

