#!/bin/sh

if [ -z "$1" ]; then 
  echo "Usage: $(basename $0) <text to find>"
  echo "       or"
  echo "Usage: $(basename $0) <text to find> [filespec. default is all files]"
  echo "       or"
  echo "Usage: $(basename $0) <text to find> [filespec. default is all files] [directory. default=.]"
else

  TEXT=$1
  shift
  if [ -n "$1" ]; then
    FILES="-name $1"
    shift
  else
    FILES=''
  fi
  if [ -n "$1" ]; then
    DIR="$1"
    shift
  else
    DIR=.
  fi

  echo "Did you exclude the node_modules directory?"
  find $DIR -type f $@ $FILES -print0 | xargs -0 grep "$TEXT"
fi

