#!/bin/bash

DIR=${1:=.}
TEXT=$2

if [[ "$TEXT" =~ ^/ ]]; then
  sh -c "find $DIR -type f | xargs grep -l $TEXT; find $DIR -wholename $TEXT " | sort | uniq | xargs ls -ld
else
  sh -c "find $DIR -type f | xargs grep -l $TEXT; find $DIR -name *$TEXT* " | sort | uniq | xargs ls -ld
fi

