#!/bin/sh

DIR=.
if [ -x "$1" ]; then
  DIR=$1
  shift
fi

if [ -n "$1" ]; then 
  OR="-o"
fi

find "$DIR" \( -name node_modules -o -name .git -o -name .idea \) -prune $OR $@ -print

#find "$DIR" -path node_modules -prune -o -path .git -prune -o -path .idea -prune $OR $@

