#!/bin/sh

# To get sizes of all objects which are used to make the history of a branch (or any definition of 
# history graph, actually). It still does not account for delta-packing or compression but gives
# precise information of how much space you'll need to store all unique data of a repository.

echo 'Cleaning up unused blobs.'
git gc --aggressive

echo 'Calculating.'
DATE=$(date +'%Y-%b-%d_%H.%M.%S')

# From: https://stackoverflow.com/questions/32557849/get-git-branch-size
git rev-list HEAD | nl | xargs -n 2 -P 8 sh -c \
    'git ls-tree -rl "$1" | perl -p -e "\$_ =~ s/[^ ]*+ [^ ]*+ ([^ ]*+) ++([^\t]*+)\t.*+/\1 \2/" | sort > /tmp/logfile_$DATE_$0' ; 
sort -m -u /tmp/logfile_$DATE_* | awk '{ sum += $2 } END { print sum }'
rm -f /tmp/logfile_$DATE_*
