#!/bin/sh

BRANCH=$1
if [ -n "$BRANCH" ]; then
    PATCH_FILE=git-move-to-branch.patch
    trap "rm -f $PATCH_FILE" EXIT 1 3 9 13 15 18 20 23
    git diff > $PATCH_FILE
    git checkout -b $BRANCH
    git apply $PATCH_FILE
else
    echo "`basename $0`: <new branch name>"
    echo "    Saves any changes, creates and switches to a new branch, then restores the changes."
fi
