#!/bin/sh

CURRENT_BRANCH="`git-current-branch`"

show_up() {
  echo "
  REMOTE: $1
  "
  git remote show $1 | grep "\(?:^  [A-Z]\|${CURRENT_BRANCH}\)"
}

show_up origin
show_up upstream

#git remote show -n upstream origin | grep 'URL:.*\.git$'

echo "
  Current Branch: $CURRENT_BRANCH
"

