#!/bin/sh

if [ -z "$1" ]; then
    echo "Usage: `basename $0` <grep args>"
    echo "       Searches for git repositories with matching URL paths."
else
    grep -A1 '\[remote "origin"\|url' */.git/config */*/.git/config 2>/dev/null | grep 'url' | grep -i $@
fi

