#!/bin/sh

URL_PATH=$1
POST_DATA_FILE=$2
shift 2

[ -n "$POST_DATA_FILE" ] && \
	curl -H 'firstName: Glen' -H 'lastName: Coakley' -H 'email: gcoakley@datarecognitioncorp.com' \
		-H 'Content-Type: application/json; charset=utf-8' -H 'User-Agent: curl' $@ \
		http://ideasdevapp01/test.ideas/$URL_PATH -d @$POST_DATA_FILE
echo ''
