#!/bin/sh

URL_PATH=$1
shift

[ -z "$URL_PATH" ] && \
	curl -H 'firstName: Glen' -H 'lastName: Coakley' -H 'email: gcoakley@datarecognitioncorp.com' \
		-H 'User-Agent: curl' $@ http://ideasdevapp01/test.ideas/$URL_PATH

echo ''