#!/bin/sh

function get_pids() { 
   me=$0
   ps -ef | grep $@ | grep -v "$me\|grep" | awk '{print $2}'
}

for signal in INT TERM KILL; do
   target_pids="`get_pids $@`"
   if [ -n "$target_pids" ]; then

      kill -$signal $target_pids

      target_pids="`get_pids $@`"
      if [ -n "$target_pids" ]; then
         sleep 2
      fi
   fi
done
