#!/bin/sh

COMPFILES=dcriatP00?/iat.log*.gz
if [ -r $COMPFILES ]; then
    gunzip $COMPFILES
fi

TMPBASE=$TMP/$(basename $0)
cd /c/dev/wksp/temp/la_prod_logs
#cat dcriatP003/iat.log* dcriatP004/iat.log* | grep '\(EDirectAuthenticationFilter\|UserActivityFilters\) ' > ${TMPBASE}.req

echo 'Request_count Hour_of_day'
cut -c 12-13 ${TMPBASE}.req | grep '[0-9][0-9]' | sort | uniq -c > ${TMPBASE}.hours
cat ${TMPBASE}.hours
awk '{print $1}' < ${TMPBASE}.hours | stats

echo 'Request_count Day_of_year'
cut -c 1-10 ${TMPBASE}.req | grep '^2017-' | sort | uniq -c > ${TMPBASE}.days
cat ${TMPBASE}.days
awk '{print $1}' < ${TMPBASE}.days | stats

# rm ${TMPBASE}*

