#!/bin/sh

# See also: myip-detail

ifconfig -ul | tr ' ' '\n' | while read if; 
do 
    addr=$(ipconfig getifaddr $if)
    if [ -n "$addr" ]; then 
	echo "$if = $addr $(ifconfig -v $if | grep '^[	]*type:')"
    fi
done

# OLD
# This depends on the format of the output but, provides more detail including the IPV6 address.
# ifconfig -v | grep '<UP\|inet' | grep -B1 inet | grep -A2 ^en
