### 'forms/' clientCode '/' formId
### ER Math Form
GET {{altFormBuilderUrl}}/live/forms/WA/ae93b27c-a1c9-42c1-b4fb-2274203e7a1c
Authorization: Bearer {{ecaBearer}}
Accept: */*
Content-Type: application/json

### ER Math Form items
GET {{altFormBuilderUrl}}/live/forms/WA/ae93b27c-a1c9-42c1-b4fb-2274203e7a1c/items
Authorization: Bearer {{ecaBearer}}
Accept: */*
Content-Type: application/json

### WA SCS (seed)
GET {{altFormBuilderUrl}}/live/forms/WA/ef394d88-0c7b-43f3-b470-cd292fb504c5
Authorization: Bearer {{ecaBearer}}
Accept: */*
Content-Type: application/json

### WA SCS (seed) form
GET {{altFormBuilderUrl}}/live/forms/WA/01a10287-1083-4f4f-9279-d61a856146fc
Authorization: Bearer {{ecaBearer}}
Accept: */*
Content-Type: application/json

### WA SCS (seed) items
GET {{altFormBuilderUrl}}/live/forms/WA/01a10287-1083-4f4f-9279-d61a856146fc/items
Authorization: Bearer {{ecaBearer}}
Accept: */*
Content-Type: application/json

### WA "Big Shoots-Response Type"
GET {{altFormBuilderUrl}}/live/forms/WA/0f6f38ee-d286-4c4e-bfe8-deaf4a9b4ef9
Authorization: Bearer {{ecaBearer}}
Accept: */*
Content-Type: application/json

###
