POST https://api-gateway-dev.drcedirect.com/eca-security-service/all-development-v0/v0/authenticate
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{ "username": "gcoakley@datarecognitioncorp.com", "password": "Password.18.1" }

<> 2018-07-16T113237.200.json

###
Replace POST content with the proper data.

DEV		https://api-gateway-dev.drcedirect.com/eca-security-service/all-development-v0/
SQA		https://api-gateway-sqa.drcedirect.com/eca-security-service/all-sqa-v0/
PROD	https://api-gateway.drcedirect.com/eca-security-service/all-production-v0/
