GET https://api-gateway-sqa.drcedirect.com/eca-security-service/all-sqa-v0/v0/user/81517887-240C-4841-8361-0381A5F4D52C
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdjb2FrbGV5QGRhdGFyZWNvZ25pdGlvbmNvcnAuY29tIiwiaWF0IjoxNTMyNzIyMTQ4LCJleHAiOjE1MzI3MjM5NDgsImlzcyI6ImVjYS1kcmMiLCJzdWIiOiI4MTUxNzg4Ny0yNDBDLTQ4NDEtODM2MS0wMzgxQTVGNEQ1MkMifQ.KohdYYXYmHeqLEBQ7wGuocmkuNG2VirErM_0H8yG1u3_g1mn9OyFhL-Sgr9Sb0jXTSsk4JvHld47FGI_peOA_qFG9DVQ6NE8uA2FuBN3wXMeC5HfEpmkiS2GDuwxNfGZ-VpWTkfDXHQFmfIpuafwzMTPtPA_11qKYAYgyyVewuNNRbDeUtGYMbLw60J4Ti7vzZQGQ3hfKV7I3pqKI-d3zLfZGNixCrKoFjw3kryKuDwUmkILMw-qklZR5XwmUy1rgBqsw0gZ8ApjHOKzP7_qw0rhu65DJ_KwnM6s55YSWDYwOezu2eiR7PUrql6J73-nfMRx7YIDFN1g3i0Ma65alg

<> 2018-07-27T031159.200.json
<> 2018-07-27T031057.401.txt
<> 2018-07-23T112415.401.txt
<> 2018-07-11T085502.200.json
<> 2018-07-11T085342.200.json

###
Replace the UUID in the URI (after '/user/') with the user id.

DEV		https://api-gateway-dev.drcedirect.com/eca-security-service/all-development-v0/
SQA		https://api-gateway-sqa.drcedirect.com/eca-security-service/all-sqa-v0/
PROD	https://api-gateway.drcedirect.com/eca-security-service/all-production-v0/

gcoakley@datarecognitioncorp.com: 81517887-240C-4841-8361-0381A5F4D52C
