GET https://api-gateway-sqa.drcedirect.com/eca-security-service/all-sqa-v0/v0/authenticateConfig
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

<> 2018-08-07T020017.200.json
<> 2018-08-07T015044.200.json
<> 2018-07-31T100813.200.txt
<> 2018-07-27T034800.200.json

###
Replace the TOKEN only in the URI (after '/authenticate/') with the ECA token value.
Don't accidentally delete the trailing '/acls'.

DEV		https://api-gateway-dev.drcedirect.com/eca-security-service/all-development-v0/
SQA		https://api-gateway-sqa.drcedirect.com/eca-security-service/all-sqa-v0/
PROD	https://api-gateway.drcedirect.com/eca-security-service/all-production-v0/
