POST https://api-gateway-sqa.drcedirecte.com/eca-security-service/all-sqa-v0/v0/refresh?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdjb2FrbGV5QGRhdGFyZWNvZ25pdGlvbmNvcnAuY29tIiwiaWF0IjoxNTMxNTE2MzQ1LCJleHAiOjE1MzE1MTgxNDUsImlzcyI6ImVjYS1kcmMiLCJzdWIiOiJEQTU2QUEwQi03NTdFLTQ5MjUtOTU4NC0wOTVDQ0Y3MjA4REQifQ.zwUwQsO4VXSIjoM2zjX7amzn2pPdeTQ6ihNuBRu9-cDz6D0ZScEr_zFKcfjvjyfOzLhpldkBqOtM8H0yqF7gfTiSO-lEzRYddGJ4sZedQHc-McoOz7ep1gVkNh6CysIwyu3JJ_3sYITrKF_1NITU3Q51wr6LY1iaBpHFBdeYB1WMaLw8An2CGTQfH4Nlk60NsztaOmyRZSZJb55Ca1y9MRA1BX0f0nU8AsCfZk5FJxTnysyzP_owZs9t55SOg0E1ouljYCSAnwn03RSiym4Et7Zr7JvVOzuqDpy_-j3wNYlPl4qbnihItUnbzW536w-KaMXCXl_TWlepSzXQyl0Q2w
Accept: */*
Content-Type: application/json

{token:"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdjb2FrbGV5QGRhdGFyZWNvZ25pdGlvbmNvcnAuY29tIiwiaWF0IjoxNTMxNTE2MzQ1LCJleHAiOjE1MzE1MTgxNDUsImlzcyI6ImVjYS1kcmMiLCJzdWIiOiJEQTU2QUEwQi03NTdFLTQ5MjUtOTU4NC0wOTVDQ0Y3MjA4REQifQ.zwUwQsO4VXSIjoM2zjX7amzn2pPdeTQ6ihNuBRu9-cDz6D0ZScEr_zFKcfjvjyfOzLhpldkBqOtM8H0yqF7gfTiSO-lEzRYddGJ4sZedQHc-McoOz7ep1gVkNh6CysIwyu3JJ_3sYITrKF_1NITU3Q51wr6LY1iaBpHFBdeYB1WMaLw8An2CGTQfH4Nlk60NsztaOmyRZSZJb55Ca1y9MRA1BX0f0nU8AsCfZk5FJxTnysyzP_owZs9t55SOg0E1ouljYCSAnwn03RSiym4Et7Zr7JvVOzuqDpy_-j3wNYlPl4qbnihItUnbzW536w-KaMXCXl_TWlepSzXQyl0Q2w"}

<> 2018-07-13T052338.400.txt
<> 2018-07-13T052204.400.txt

###
