GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc/passages/LA/870972
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdDb2FrbGV5IiwiaWF0IjoxNTQyNDA1NDA5LCJleHAiOjE1NDI0MDcyMDksImlzcyI6ImVjYS1kcmMiLCJzdWIiOiIzODg0QkIyMS0yREZCLTQ3QUYtQTgyQS0xQzEwMjRDODBERkMifQ.f-6XymdHSLu4qdD3q4owrgZ20fye7BrZ4YHVd7pbcEoHZ9xEiPUnpme32Cfc7TMsOnTMZ6zcBkt7AKEo2WgxbwNvURITjfvfJ8tp_iFZ7nu9dicgrxrxBo_sdCZY2MlGbuk2mZCaVO2kqKmpD5zi-vCldKquVcx7-CkHHc_SXXfS9BCdCh__QGzbV-SoTEmM0B4OKkV_mYyypQyC3UkNFAisFAP4E6ml3XmlJS37NdHBYh4is858XnAbY17k0z28KZgK1K2bN0b13AIOOlaX00U8X3UBX9K3_6l57UumRMfdHarmZe3pIH1XHbWP4Q0xxpSn1SdG6nRU9ItZhpa9oA

<> 2018-10-01T115641.403.json
<> 2018-10-01T104938.403.json
<> 2018-10-01T104622.403.json
<> 2018-09-28T074843.200.json
<> 2018-09-26T114231.200.json
<> 2018-09-26T114204.200.json
<> 2018-09-26T114109.403.json
<> 2018-09-06T090946.200.json
<> 2018-09-05T023226.200.json
<> 2018-08-07T095852.200.json
<> 2018-08-07T095844.404.json
<> 2018-08-06T122845.200.json
<> 2018-07-11T084242.200.json

###
# Different environment URIs
# GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
# GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
# GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc
#
# Using Edirect
# SQA: http://ideasdevapp01/test.ideas/webservices/REST/1.0/iat.svc
# Prod: http://dcwidap014/ideas/webservices/REST/1.0/iat.svc
