GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc/itemsandcount/LA?query=((itstatus%3DExternal%2CFTReady%2CData%2COPReady)%2C(itprojectcode%3DELA842%2CELA_IAT)%2C(itpublic%3DTrue)%2C(pspassageid%3D127576-127576))&searchId=113494
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdDb2FrbGV5IiwiaWF0IjoxNTM2MjQyMjMyLCJleHAiOjE1MzYyNDQwMzIsImlzcyI6ImVjYS1kcmMiLCJzdWIiOiJGOUVCQUIwQS1FNDJDLTRGMDctOUUwMy04RUEzQzU0NTE5QTEifQ.w6_ZPaN1Gh3Pm36WqodaoHW8Lt0VI1TW_X4yqIa3ZpmtNtWRWW3eFHuos98pO6zlpQrOR8q2Zs1lbb16262lzun2iateKjeRVmgTJ6iFBln_e0CHNWG5LMPBwcR1T2n48QUZABf5DxVPyRApZH4o58MXPjENRxNee4MjGnGS3h6-V7uQwzVeVVOTBWxJLiSYvtq-BC8HAD6ICuRwha0GLvvPqtAV6VliUFTP_-eMNsaoxHrhmNAEPkQ_wEri-uLKcCSItD7nds1v4ZdHJFc1Uy271rJ14zOaL6OTTM3ybSaQ7ACjLEhsVx3xHtIsWRuXirZKntBkYat8cyD4bMWgjg

<> 2018-09-06T085748.200.json
<> 2018-09-06T085618.403.json
<> 2018-09-06T085600.403.json
<> 2018-09-06T085449.200.html
<> 2018-08-06T124239.400.json
<> 2018-08-06T122845.200.json
<> 2018-07-11T084242.200.json

###
Different environment URIs:
GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc

Using Edirect:
SQA: http://ideasdevapp01/test.ideas/webservices/REST/1.0/iat.svc
Prod: http://dcwidap014/ideas/webservices/REST/1.0/iat.svc
