GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc/items/LA/1006470
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdjb2FrbGV5QGRhdGFyZWNvZ25pdGlvbmNvcnAuY29tIiwiaWF0IjoxNTQ0NjQ2NDkwLCJleHAiOjE1NDU0ODUyOTAsImlzcyI6ImVjYS1kcmMiLCJzdWIiOiJEQTU2QUEwQi03NTdFLTQ5MjUtOTU4NC0wOTVDQ0Y3MjA4REQifQ.FdSfLwTPKE9SH9LLqszY5agPwc8AvcHEw-W4mIEDk9sD0JGHqjlcoc2VcxJ3WkjVQ_cRunZSxdTX97sPV3QUM_axEqiZIwPyvP_UJtQ3igK582vc_oGiFj0Fw5GtEfm5xaB2v3rcxcp_UlIajkZOwchRrfjInMTYhQLGY6uM6rTiZaCfvLkp7IgZ3KK5grLYPmjjNBLp9i275TFrJ3Mua3Y1fUPx84KIpUYkT4rAtxXxcJN3ptR3lRt4ju5RgByq65a9K-j9mPmpQ3vHXoACjtFtJtHbI1q2KuyOJYTzud1WVq-snQUYdNPGjIw27pWO_G44wfX_SfqMXuBcZdNj0w

<> 2018-10-08T085109.200.json
<> 2018-10-08T085021.403.json
<> 2018-10-08T020219.200.json
<> 2018-10-07T084114.200.json

###
# Different environment URIs:
#   GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
#   GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc
#
# Using Edirect:
#   SQA: http://ideasdevapp01/test.ideas/webservices/REST/1.0/iat.svc
#   Prod: http://dcwidap014/ideas/webservices/REST/1.0/iat.svc
