GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc/items/LA/1014204
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdjb2FrbGV5QGRhdGFyZWNvZ25pdGlvbmNvcnAuY29tIiwiaWF0IjoxNTQyNzQwODE5LCJleHAiOjE1NDM1Nzk2MTksImlzcyI6ImVjYS1kcmMiLCJzdWIiOiI4MTUxNzg4Ny0yNDBDLTQ4NDEtODM2MS0wMzgxQTVGNEQ1MkMifQ.oV48F4MFsxoiPzdWYPQnM1R-Iax29zIvvdWv2rnnPAuSbIzLOgeGvQ_susaoChbPNla4n9dczFKmp2ts56PSwUwDGDZTjpKORpZ1RoNedTGpF6wm7Vmvz4B7euXhjJo4wSN4CGZihK-3mmQD1BDxKDV2fwO1ECYkYnq_tZblNA4yXg-hIVTGJoXfeoTAL7Vz8leGC2Om-LCyeHSsX7ZpDZkzISfrCqy8lNDvRYuALD2rOGYs47iBihHbUi_DXfderW2T14U83e0IHTq9rVUBxSqj2MtocdyTOPZ1Cas5i9fQ7peMDcrMOZbmteBL7-zC0zr370yPW8BBEiN0k1AOoQ

<> 2018-10-08T085109.200.json
<> 2018-10-08T085021.403.json
<> 2018-10-08T020219.200.json
<> 2018-10-07T084114.200.json

###
# Different environment URIs:
#   GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
#   GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc
#
# Using Edirect:
#   SQA: http://ideasdevapp01/test.ideas/webservices/REST/1.0/iat.svc
#   Prod: http://dcwidap014/ideas/webservices/REST/1.0/iat.svc
