GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc/items/LA/1019096
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdjb2FrbGV5QGRhdGFyZWNvZ25pdGlvbmNvcnAuY29tIiwiaWF0IjoxNTQ5NDc5OTU3LCJleHAiOjE1NDk0ODE3NTcsImlzcyI6ImVjYS1kcmMiLCJzdWIiOiJEQTU2QUEwQi03NTdFLTQ5MjUtOTU4NC0wOTVDQ0Y3MjA4REQifQ.hc5qEjhwrrarzksPQoU4R43Py-BbRI2P-413XAb6nMwPFbLmHyImimcVvhh9_gxha1xzYdir0zU6teGubT5n35fUoArpx8sbPh-hRTz81HoziI_m7mK_WzLM4_q76kefln6vMRU4LUU-6b4JSJpx8PzAKnJocK7gFG58qF2bDHVMkVjBT0NOGFUpJW8aPoid9qpHNVUvhZ_VN5cXEXlv5XYvkM8hYrQzOWgwxBn6yB02Z_Rl8q_jFIfT_TG2Y8G55-ReZ2mC1cvZKdKQdh08yWrdgif7sPh3QXLLUsmFiKyrU5aX5NiGg1bUVQ_quwmVM3_UAWjKf2AwyuVdwf2y2A

<> 2018-10-08T085109.200.json
<> 2018-10-08T085021.403.json
<> 2018-10-08T020219.200.json
<> 2018-10-07T084114.200.json

###
# Different environment URIs:
#   GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
#   GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc
#
# Using Edirect:
#   SQA: http://ideasdevapp01/test.ideas/webservices/REST/1.0/iat.svc
#   Prod: http://dcwidap014/ideas/webservices/REST/1.0/iat.svc
