GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc/items/LA/1014204
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdjb2FrbGV5QGRhdGFyZWNvZ25pdGlvbmNvcnAuY29tIiwiaWF0IjoxNTQ4Mjg1NzczLCJleHAiOjE1NDgyODc1NzMsImlzcyI6ImVjYS1kcmMiLCJzdWIiOiI4MTUxNzg4Ny0yNDBDLTQ4NDEtODM2MS0wMzgxQTVGNEQ1MkMifQ.XWupfcu2fGH5FqeEwj6QKKAQOUgNrz4wYABSeHWH4rV8VgQmgIOrx_-OJIjnJ-Gz9P3_4AozMhzqD7NmzFcIzzmeMeL4PtSSAL3QkfQrQ1M_tu8C9wfBa6yVWGcHsrRX11xXFWIdFQJXDn3iIl2e3mI_apRAj25UR4xRMnKgeTtmSuqqK8JIxXhs_zH4VUL2gbZyjw76qhqndqCKpyJMiMGx333vYgbUOb54IX8vXg2xpj7w8RbbfkzvVdn5RGE6WpogEN9W0Il_QY5NSvUt08SBZtZ7MH4Hia1uicgBFGO9I3aX1i0wFvYNvbFtHDMQLRcI5W1LYLqbNSto6y9G5w

<> 2018-10-08T085109.200.json
<> 2018-10-08T085021.403.json
<> 2018-10-08T020219.200.json
<> 2018-10-07T084114.200.json

###
# Different environment URIs:
#   GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
#   GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc
#
# Using Edirect:
#   SQA: http://ideasdevapp01/test.ideas/webservices/REST/1.0/iat.svc
#   Prod: http://dcwidap014/ideas/webservices/REST/1.0/iat.svc
