GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc/items/LA/1014445
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdjb2FrbGV5QGRhdGFyZWNvZ25pdGlvbmNvcnAuY29tIiwiaWF0IjoxNTQ4MjY1MzUzLCJleHAiOjE1NDgyNjcxNTMsImlzcyI6ImVjYS1kcmMiLCJzdWIiOiI4MTUxNzg4Ny0yNDBDLTQ4NDEtODM2MS0wMzgxQTVGNEQ1MkMifQ.0qWHUdvwCQ2Ec4kqEXkknbjiO8IYOIwaXgHufUNFXePPz3_jj_qgOKqM42cjacRryhnQPt-ZYg1uMo18S5Q2ZBlG4RDeP9vOrILJNYnkXxqZyhHl_iu4fr3j52iT1E96rvyQIBXXUaykKxHW4gtyiB63a5Osmg85DvVACqq5TlNOCrtklh0acVwQYQ5h1Lc-JdmDF3ucXBeDWrMIvc0LaZw0aO5q5VB65x69g1TU3tvJz2Xuhmi07vfRJGFmnv0S5p1-_VlG55w9DPqgYPwgoHx2suhPNR1gwVxffQR00w213VWXXKO7w1XwhRjoh1bSYjyZOvg8RVDjEQMWrqmqkw

<> 2018-10-08T085109.200.json
<> 2018-10-08T085021.403.json
<> 2018-10-08T020219.200.json
<> 2018-10-07T084114.200.json

###
# Different environment URIs:
#   GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
#   GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc
#
# Using Edirect:
#   SQA: http://ideasdevapp01/test.ideas/webservices/REST/1.0/iat.svc
#   Prod: http://dcwidap014/ideas/webservices/REST/1.0/iat.svc
