GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc/items/LA/1013755
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdjb2FrbGV5QGRhdGFyZWNvZ25pdGlvbmNvcnAuY29tIiwiaWF0IjoxNTQ0ODM0NDQ1LCJleHAiOjE1NDQ4MzYyNDUsImlzcyI6ImVjYS1kcmMiLCJzdWIiOiI4MTUxNzg4Ny0yNDBDLTQ4NDEtODM2MS0wMzgxQTVGNEQ1MkMifQ.Zz7glg5ehrGD6Zzvk3mEyDXaaPV0LfMnHWYoZCx7S3VnvlStl9Eqp1dyXbuQpYgKRuFCU-bTm9rbP8RFA8Ok86PvMEjHpy_3ecMQ9YKzXuwyrfsJzcPpl-7xgjmqRLGnwNd3M25QeETezEc0m2PNzZLY2Fohbfji5d_WK_2gMl6LpnmUGlqqW6FEFKmox5anwpXjyV-0XV1gdapzaMw8mWRr74yuFfjml8YMblpem-HZ6zft7PlCYkEJ08W2SCMmIog4IYXh-QML95Al58c6Sohv8Z0aH5Qxw9a2rJg-IDU2j3Y_aAMT0w7-UctLKV9CjjAbZfXxCK_qmeM_8WBEDg

<> 2018-10-08T085109.200.json
<> 2018-10-08T085021.403.json
<> 2018-10-08T020219.200.json
<> 2018-10-07T084114.200.json

###
# Different environment URIs:
#   GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
#   GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc
#
# Using Edirect:
#   SQA: http://ideasdevapp01/test.ideas/webservices/REST/1.0/iat.svc
#   Prod: http://dcwidap014/ideas/webservices/REST/1.0/iat.svc
