GET http://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc/login/81517887-240c-4841-8361-0381a5f4d52c
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdjb2FrbGV5QGRhdGFyZWNvZ25pdGlvbmNvcnAuY29tIiwiaWF0IjoxNTQ3NTg2Mjc4LCJleHAiOjE1NDc1ODgwNzgsImlzcyI6ImVjYS1kcmMiLCJzdWIiOiI4MTUxNzg4Ny0yNDBDLTQ4NDEtODM2MS0wMzgxQTVGNEQ1MkMifQ.il7_nLYj8tKyRh7AEYjcq3jVUnwvE1Y_cF1sORZm5a-7-1ZX_q-EIlE2MCEU3r1kiWj8pUOh-Nm97WNQLamDdn2S7NrQmjPWLt_Cc0NZLMxjFHo7Ihv-JzRUVmYn35fv-XMKYrP9X0BzEswRKZB56RyCqpW3QppOqpvbLceSgWSg_lrgSKnXPTbdIoEmbQTadf3ROecoxznvATQq0qLC2EUbC_lqhzUjUIoKtJ6x0XcWiQFHLrRmYTsEAyJVzyxYOXtwAHu9vXT4puOan0lZSYo219ho-AOK8lskdchzmANm8Tx556jJGm11OO7fDsolcx7qCbRIModvv7u_jcRaMg
firstName: Glen
lastName: Coakley
email: gcoakley@datarecognitioncorp.com

<> 2018-07-11T084948.403.json
<> 2018-07-11T084537.404.html
<> 2018-07-11T084457.400.html
<> 2018-07-11T084426.400.html
<> 2018-07-09T035203.400.html

###
# Different environment ECA URIs:
# SQA:  GET https://ideasweb-sqa.drcedirect.com/sqa.ideas/webservices/REST/1.0/iat.svc
# PROD: GET https://ideasweb.drcedirect.com/ideas/webservices/REST/1.0/iat.svc
#
# Using Edirect:
# SQA: http://ideasdevapp01/test.ideas/webservices/REST/1.0/iat.svc
# Prod: http://dcwidap014/ideas/webservices/REST/1.0/iat.svc
